#!/bin/bash

# Quit Vivaldi
osascript -e 'quit app "Vivaldi.app"'

# Find path to Framework folder of current version and save it as variable
findPath="$(find /Applications/Vivaldi.app -name Vivaldi\ Framework.framework)"

# Copy custom JavaScript modules based on new folder structure

# Essential
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/aminought/ybAddressBar.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/easyFiles.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/elementCapture.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/dialogTab.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Other/autoHidePanel.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/tidyTitles.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/tidyTabs.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/clearTabs.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/immersiveAddressbar.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/wrapToday.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/tabScroll.js "$findPath"/Resources/vivaldi/

# Need to Clarify
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/accentMod.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/activateTabOnHover.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/mainbar.js "$findPath"/Resources/vivaldi/

# Optional
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/moonPhase.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/monochromeIcons.js "$findPath"/Resources/vivaldi/
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/globalMediaControls.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/aminought/chroma.min.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/aminought/colorTabs.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/importExportCommandChains.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/collapseKeyboardSettings.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/luetage/backupSearchEngines.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/adaptiveWebPanelHeaders.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/feedIcon.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Tam710562/mdNotes.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/SuperPins.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/TidyDownloads.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/vivaldi-dashboard-camo.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/Vividly.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/ClickAddBlockList.js "$findPath"/Resources/vivaldi/
#cp /Users/acid/Desktop/VivaldiModpack/moddings/colorful_loading_top_bar.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/moddings/moreFuncInWebPanel.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/moddings/widgets.js "$findPath"/Resources/vivaldi/
# cp /Users/acid/Desktop/VivaldiModpack/moddings/yb_address_bar.js "$findPath"/Resources/vivaldi/

########################################################################################################################
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/PageAction/Follower-Tabs.js "$findPath"/Resources/vivaldi/user_files
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/PageAction/TabsLock.js "$findPath"/Resources/vivaldi/user_files
cp /Users/acid/Desktop/VivaldiModpack/Javascripts/Other/Picture-in-Picture.js "$findPath"/Resources/vivaldi/components/picture-in-picture

# Save path to browser.html as variable
browserHtml="$findPath"/Resources/vivaldi/window.html

# Backup original file
cp "$browserHtml" "$browserHtml".bak

# Insert references, if not present, and save to temporary file
sed -i '' -e '/<body>/,/<\/body>/ {
    /<body>/!{
        /<\/body>/!d
    }
}' "$browserHtml"

sed -i '' -e '/<\/body>/i\
<script src="tidyTitles.js"></script>\
<script src="tidyTabs.js"></script>\
<script src="clearTabs.js"></script>\
<script src="wrapToday.js"></script>\
<script src="tabScroll.js"></script>\
<script src="immersiveAddressbar.js"></script>\
<script src="monochromeIcons.js"></script>\
<script src="ybAddressBar.js"></script>\
<script src="elementCapture.js"></script>\
<script src="globalMediaControls.js"></script>\
<script src="autoHidePanel.js"></script>\
<script src="easyFiles.js"></script>\
<script src="dialogTab.js"></script>\
<script src="moonPhase.js"></script>\
' "$browserHtml"

# <script src="accentMod.js"></script>\
# <script src="activateTabOnHover.js"></script>\
# <script src="backupSearchEngines.js"></script>\
# <script src="importExportCommandChains.js"></script>\
# <script src="feedIcon.js"></script>\
# <script src="adaptiveWebPanelHeaders.js"></script>\
# <script src="collapseKeyboardSettings.js"></script>\
# <script src="mainbar.js"></script>\
# <script src="mdNotes.js"></script>\
# <script src="chroma.min.js"></script>\
# <script src="colorTabs.js"></script>\
#<script src="vivaldi-dashboard-camo.js"></script>\
#<script src="daily-wrap.js"></script>\
#<script src="SuperPins.js"></script>\
#<script src="Vividly.js"></script>\
#<script src="TidyDownloads.js"></script>\
#<script src="ClickAddBlockList.js"></script>\
#<script src="colorful_loading_top_bar.js"></script>\

# Pause script
read -rsp $'Press [Enter] to restart Vivaldi...\n'

# Open custom files in text editor
# open "$findPath"/Resources/vivaldi/style/custom.css
# open "$findPath"/Resources/vivaldi/custom.js

# Open Vivaldi
open /Applications/Vivaldi.app --args --debug-packed-apps --silent-debugger-extension-api
# open /Applications/Vivaldi.app
