@echo off
REM Vivaldi JS Mods Installer for Windows
REM Automatically patches Vivaldi to load custom JavaScript mods
REM 
REM Original by: debiedowner
REM Editor: Phobos
REM Source: https://forum.vivaldi.net/topic/10592/patching-vivaldi-with-batch-scripts

cd "%~dp0"

set installPath="%localappdata%\Vivaldi\Application\"
echo Searching for Vivaldi at: %installPath%

for /f "tokens=*" %%a in ('dir /a:-d /b /s %installPath%') do (
    if "%%~nxa"=="window.html" set latestVersionFolder=%%~dpa
)

if "%latestVersionFolder%"=="" (
    echo ERROR: No window.html found. Is Vivaldi installed?
    pause & exit /b 1
) else (
    echo Found Vivaldi version folder: "%latestVersionFolder%"
)

if not exist "%latestVersionFolder%\window.bak.html" (
    echo Creating backup of original window.html...
    copy "%latestVersionFolder%\window.html" "%latestVersionFolder%\window.bak.html"
    echo Backup created: window.bak.html
)

set jsFolder=%~dp0..\Awesome-Vivaldi\Javascripts
if not exist "%jsFolder%" (
    echo ERROR: Awesome-Vivaldi/Javascripts folder not found.
    echo Please clone Awesome-Vivaldi first:
    echo   git clone https://github.com/PaRr0tBoY/Awesome-Vivaldi.git
    pause & exit /b 1
)

echo.
echo Combining JS mods into custom.js...
echo // Awesome-Vivaldi JS Mods - Combined > "%latestVersionFolder%\custom.js"
echo // Generated by VivaldiMods install script >> "%latestVersionFolder%\custom.js"
echo. >> "%latestVersionFolder%\custom.js"

REM Root level JS files
for %%f in ("%jsFolder%\*.js") do (
    echo Adding: %%~nxf
    echo. >> "%latestVersionFolder%\custom.js"
    echo // === %%~nxf === >> "%latestVersionFolder%\custom.js"
    type "%%f" >> "%latestVersionFolder%\custom.js"
)

REM Tam710562 mods (easyFiles, elementCapture, globalMediaControls, mdNotes, etc.)
if exist "%jsFolder%\Tam710562" (
    for %%f in ("%jsFolder%\Tam710562\*.js") do (
        echo Adding: Tam710562/%%~nxf
        echo. >> "%latestVersionFolder%\custom.js"
        echo // === Tam710562/%%~nxf === >> "%latestVersionFolder%\custom.js"
        type "%%f" >> "%latestVersionFolder%\custom.js"
    )
)

REM aminought mods (colorTabs, ybAddressBar)
if exist "%jsFolder%\aminought" (
    for %%f in ("%jsFolder%\aminought\*.js") do (
        echo Adding: aminought/%%~nxf
        echo. >> "%latestVersionFolder%\custom.js"
        echo // === aminought/%%~nxf === >> "%latestVersionFolder%\custom.js"
        type "%%f" >> "%latestVersionFolder%\custom.js"
    )
)

REM luetage mods
if exist "%jsFolder%\luetage" (
    for %%f in ("%jsFolder%\luetage\*.js") do (
        echo Adding: luetage/%%~nxf
        echo. >> "%latestVersionFolder%\custom.js"
        echo // === luetage/%%~nxf === >> "%latestVersionFolder%\custom.js"
        type "%%f" >> "%latestVersionFolder%\custom.js"
    )
)

REM PageAction mods
if exist "%jsFolder%\PageAction" (
    for %%f in ("%jsFolder%\PageAction\*.js") do (
        echo Adding: PageAction/%%~nxf
        echo. >> "%latestVersionFolder%\custom.js"
        echo // === PageAction/%%~nxf === >> "%latestVersionFolder%\custom.js"
        type "%%f" >> "%latestVersionFolder%\custom.js"
    )
)

echo.
echo Patching window.html...
type "%latestVersionFolder%\window.bak.html" | findstr /v "</body>" | findstr /v "</html>" > "%latestVersionFolder%\window.html"
echo     ^<script src="custom.js"^>^</script^> >> "%latestVersionFolder%\window.html"
echo   ^</body^> >> "%latestVersionFolder%\window.html"
echo ^</html^> >> "%latestVersionFolder%\window.html"

echo.
echo ========================================
echo Done! JS mods installed successfully.
echo ========================================
echo.
echo Included mods:
echo   - tidyTabs.js (AI tab grouping)
echo   - tidyTitles.js (AI title cleanup)
echo   - ClearTabs.js (clear inactive tabs)
echo   - immersiveAddressbar.js (immersive theme)
echo   - globalMediaControls.js (media panel)
echo   - elementCapture.js (screenshots)
echo   - easyFiles.js (quick file picker)
echo   - mdNotes.js (markdown notes)
echo   - colorTabs.js (colored tab borders)
echo   - feedIcon.js (RSS feed icons)
echo   - dialogTab.js (open in dialog)
echo   - importExportCommandChains.js
echo   - and more...
echo.
echo Restart Vivaldi to apply changes.
echo To restore: run restore-vivaldi.bat
echo.
pause
